name: Test Action
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get NPM cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - run: npm ci
      - run: npm run build --if-present
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          patterns: ./index.js
